### ISSUE TITLE
Edit link broken for Sharable Glossaries docs

### ISSUE THREAD

**Issue by sivaraam** [thegooddocsproject/website-hugo#105]
I was look at [a doc](https://thegooddocsproject.dev/docs/glossaries/maturity-levels/) related to sharable glossaries and noticed one thing that could be changed. So, I used the "Edit this page" button. It appears to take me to a 404 page. The URL is:

https://github.com/thegooddocsproject/website-hugo/edit/master/content/en/docs/glossaries/maturity-levels.md

On a closer look, it looks like the edit URL is for the `master` branch while the default branch for this repo appears to be `main`. I looked for some way to correct this by changing some kind of configuration but couldn't find any. So, filing this issue.

**Comment by bwklein** [comment]
Added the `github_branch` config parameter to the Hugo config.toml file and the links work now as expected.

**Comment by sivaraam** [comment]
I somehow still get a 404 page when I try to access [this doc](https://thegooddocsproject.dev/docs/glossaries/maturity-levels/). Was the change deployed? 🤔

**Comment by zivbk1** [comment]
@sivaraam no it is currently in the blog test branch.  I'll make a new branch to get this change into production now, since it could be a while longer to release all the updates in the blog branch.
