### ISSUE TITLE
Remove Base Template working group page

### ISSUE THREAD

**Issue by barbaricyawps** [thegooddocsproject/website-hugo#113]
We need to remove the Base Template working group from the website: https://thegooddocsproject.dev/working-group/base-template/

The Base Template group is no longer active because it is being superseded by a different group (a meeting of the template leads).

To remove:

1. Delete the `base-template.md` file in `content/en/working-group/` folder.
2. After opening a PR, check the rendered content to see if it stops displaying on the [Working groups](https://thegooddocsproject.dev/working-group/) page

**Comment by barbaricyawps** [comment]
By the way, please don't work on this ticket yet. I generated these "good first issue" tickets for a demo Git training we're doing in the Community Docs working group in 2 weeks.

**Comment by deanna-cs** [comment]
@barbaricyawps When you say "check the rendered content", do you mean preview the site locally? Or would we have them view the site after merging in the PR?

**Comment by barbaricyawps** [comment]
@deanna-cs , I don't think I see this in the Contributing guide for this repo, but basically when you open a PR, there's a Netlify build that allows you to preview a build of your site. I can demo that. And... as a follow up we can add that to the Contributing Guide!

**Comment by bwklein** [comment]
> @barbaricyawps When you say "check the rendered content", do you mean preview the site locally? Or would we have them view the site after merging in the PR?

@deanna-cs If you use Gitpod, it is setup to run a live preview of the site while you are editing.  The system will also build a branch preview for the PR so you can share that link after the GitPod workspace is shutdown.
