### ISSUE TITLE
Remove How to Contribute page

### ISSUE THREAD

**Issue by barbaricyawps** [thegooddocsproject/website-hugo#116]
I think the [How to Contribute page](https://thegooddocsproject.dev/contribute/) is a duplicate of the content on the [Community page](https://thegooddocsproject.dev/community/) and should be removed so that we have one source of truth.

To remove:

1. Delete the `contribute.md` file in `content/en/` folder.
2. Remove the link to this file on line 90 in the Additional resources section on the `content/en/community.md` file.
3. After opening a PR, check the rendered content to see if it stops displaying on the Community file.

**Comment by AjRadwan** [comment]
Hello, @barbaricyawps I check out both of the files and I don't think both of the pages have the same content. and the community page has a link to contribute page at the bottom **Additional resources and information and info** section,
do you mind checking it again if there is any need to remove the page?

**Comment by barbaricyawps** [comment]
@AjRadwan , the content is not an exact word-for-word duplicate, but I think it's out of date and the most up to date version is on the community page.

By the way, please don't work on this ticket yet. I generated these "good first issue" tickets for a demo Git training we're doing in the Community Docs working group in 2 weeks.

**Comment by AjRadwan** [comment]
Okay,, I Won't work on it Than,  Have a good day
