### ISSUE TITLE
Change headings that use -ing on Licenses page

### ISSUE THREAD

**Issue by deanna-cs** [thegooddocsproject/website-hugo#133]
We follow [Google's Style Guide](https://developers.google.com/style/headings), which says that "When possible, avoid using -ing verb forms as the first word in any heading or title."

Some recent edits to the [Licenses](https://thegooddocsproject.dev/licenses/) page accidentally introduced the -ing form to some headings. Let's change them to simple verbs for easier localization.

To edit the page:
- Open the license.md file in content/en/ folder.
- Convert the headings from -ing form to simple verb forms.

**Comment by barbaricyawps** [comment]
Resolved by https://github.com/thegooddocsproject/website-hugo/pull/135
