### ISSUE TITLE
Rename "image" in YAML header to "splash"

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#164]
I'd like to keep those variables to have contextual names, and since that's the splash image, we can use "splash." And if we end up having other images later, we can keep those contextual as well so we start with disambiguation.

**Comment by ryanmacklin** [comment]
Not a blocker for Portland

**Comment by bwklein** [comment]
This is the first time I have heard the term 'splash image'.  I didn't find it when googling either.  Where does that term come from?

**Comment by ryanmacklin** [comment]
May be one of those "Ryan has been in content & publishing for years". What about "header-image"?

**Comment by bwklein** [comment]
Hugo looks for images with the words *feature*, *cover* or *thumbnail* in the filename for some of the internal templates.  Do any of those terms resonate?

**Comment by ryanmacklin** [comment]
Cover sounds good to me. i feel like "feature" might be like a special inline sort of connodation, so let's go with cover.

**Comment by bwklein** [comment]
We can change the title of it in the CMS UI to something like 'Cover Image', but I am going to stick with image and images in yaml front matter because they are used in internal templates and shortcodes.
