### ISSUE TITLE
Migrate - Contribute

### ISSUE THREAD

**Issue by bwklein** [thegooddocsproject/website-hugo#22]
_Originally posted by @bwklein in https://github.com/thegooddocsproject/website-hugo/issues/9#issuecomment-725749643_

From: https://thegooddocsproject.dev/contribute.html

Source: https://github.com/thegooddocsproject/thegooddocsproject.github.io/blob/master/contribute.md

Note: Maybe link to a governance document? @barbaricyawps

**Comment by barbaricyawps** [comment]
Looks like @Loquacity might be working on this issue: https://github.com/thegooddocsproject/templates/issues/171

**Comment by barbaricyawps** [comment]
See this pull request: https://github.com/thegooddocsproject/templates/pull/172/files

**Comment by Loquacity** [comment]
Ah, apologies for the duplication.

**Comment by bwklein** [comment]
@Loquacity there's no problem at all, we just want to make sure we have the right version linked to or reproduced in text on the new website.  Thank you for helping sort it out.
