### ISSUE TITLE
Migrate - Licenses

### ISSUE THREAD

**Issue by bwklein** [thegooddocsproject/website-hugo#24]
_Originally posted by @bwklein in https://github.com/thegooddocsproject/website-hugo/issues/9#issuecomment-725749643_

From: https://thegooddocsproject.dev/licences.html

Source: https://github.com/thegooddocsproject/thegooddocsproject.github.io/blob/master/licences.md

Maybe links to other resources? @barbaricyawps

**Comment by barbaricyawps** [comment]
I posted a discussion topic to the Good Docs mailing list for more clarification about the license for GDP:

> I'm assisting Bryan K with the conversion of the Good Docs website to Hugo/Docsy where I can. I agreed to take on the action item to confirm which license we're using for the Good Docs project. Currently the templates repo is using the Zero-Clause BSD license, but I know there were some talks that Google might want us to use Creative Commons if they are going to give us some of their internal templates. (Was it Creative Commons or something else? I can't 100% remember.)

> Since changing our license is a big deal that requires community input and discussions, should we just use the existing Zero-Clause BSD on the Good Docs website now or should we begin the discussion about changing our license?

I'll let you know what I hear back from the group.

**Comment by barbaricyawps** [comment]
I got some more clarity from Cameron in response to my question about the licenses yesterday.

The crucial bit of information here is: **"I suggest we stick with Zero-BSD until 1) We get legal advice and 2) We put to our community and get a vote."**

Here's Cameron's full response:

> The license we'd want to select is CC-By (not sure which version, or whether the version matters). It is likely that a response from Google legal on license status may take a while, and we shouldn't have any of our initiatives be blocked by waiting
on Google. So I suggest we stick with Zero-BSD till: 1. We get legal advice, 2. We put to our community and get a vote.

> Our previous selection of Zero BSD license for templates was to ensure that people can use our templates to build their project's main page, and not need to have obvious license attribution on their front page.

> I've since heard that there are work-arounds that can be applied to a CC-By which should be suitable. (E.g. put the attribution statement in HTML comment). But I'm waiting for that to be provided in writing.

**Comment by barbaricyawps** [comment]
FYI, you can get the full text of the Zero-BSD license here: https://github.com/thegooddocsproject/templates/blob/master/LICENSE.txt

**Comment by mgan59** [comment]
Opened a PR for review, left a comment as a followup to style and update the content to include the full-snippets for each license agreement.
