### ISSUE TITLE
Make new table for meeting times in different time zones

### ISSUE THREAD

**Issue by zivbk1** [thegooddocsproject/website-hugo#34]
Content update: "feel like our times are fairly stable we could probably do a table and give days/times for the meetings.  I think we show different timezones (seen this in other projects) and as a US based member felt that was one of the first hurdles was figuring out when the meeting was because it was given to me in Australia time 😉"

_Originally posted by @mgan59 in https://github.com/thegooddocsproject/website-hugo/pull/31#discussion_r532028944_

**Comment by barbaricyawps** [comment]
I think this issue is resolved with our new meeting calendar: https://thegooddocsproject.dev/community/
