### ISSUE TITLE
Summary all our non-trivial initiatives

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/website-hugo#36]
We don't have a good way to show the active status of each of the initiatives we are working on. (There are about 10 initiatives running in parallel, and another 10 to 20 initiatives in the pipeline waiting for an interested party to take them on.)

This would be very useful when onboarding new volunteers who are wondering how they can help.

I suggest that we set up a directory structure where each initiative can have its own "elevator pitch" front page.

It should:
* Be short, easy to maintain and easy to skim read - say two paragraphs.
* Explain what the initiative in a sentence or two.
* Include a status, which we periodically updated. We probably should make a call out to all projects every 3 months to update their status.
* Mention something about schedule.
* Included last time this page was updated.
* Include a point of contact (a real person who you can reach out to). 
* Include communication channels, such as slack of email list.
* Potentially point to the home page of the initiative.

**Comment by camerons** [comment]
A starting point for what we are working on. I'm sure to have missed some projects. I've just included a suggested point of contact, not all people involved in the initiative.
*   [Information Architecture Guide](https://github.com/thegooddocsproject/incubator/tree/master/ia-guide) (Lana)
    *   Google Season of Docs (Lana, Jared, Morgan)
*   [Draft base template](https://github.com/thegooddocsproject/incubator/tree/master/base-template), to help with creating new templates (Viragi, Lana, Cameron)
*   Improvements to our [core doc type templates](https://github.com/thegooddocsproject/templates) (All, more work needed)
*   [Guide for building a Style Guide](https://github.com/thegooddocsproject/incubator/tree/master/style-guide) (Alyssa)
*   Initial results from the [Glossary pilot](https://docs.google.com/document/d/1Fjrl34ErnYammel9WmvXJ3rMWFANjoSiiGyyNSYOXUg/edit).  (Cameron, Ankita, Naini)
*   Set up of the [incubation repository](https://github.com/thegooddocsproject/incubator) (Morgan)
*   [Hugo site migration](https://github.com/thegooddocsproject/website-hugo) (Bryan, )
*   Improved rigor in git contributor tooling, git hooks etc. - (Morgan, )
*   Slack bots (Aidan, )
*   Standard github doc pages to lift our project [health](https://github.com/thegooddocsproject/.github) scores (Alyssa)
*   Maturing of [our community processes](https://thegooddocsproject.dev/community.html) (Cameron, Erin, others)
*   [Draft persona definitions](https://github.com/thegooddocsproject/incubator/pull/11) (Aaron)
*   [Chronologue example project](https://github.com/thegooddocsproject/chronologue) (Erin, Felicity)
*   Knocking over bugs (Aidan, Aaron)
*   Aggregating Code of Conducts together (Alyssa)
*   [Tech Writer Patterns, Anti-patterns and Tasks](https://docs.google.com/document/u/1/d/1Uo3Rcc-rRaN4kmJpqwtUaVRJmDbYI4TkwjuNWNuBu9A/edit#) (Cameron)
    *   Roadmap of tasks
*   Presenting at events
*   [Proposal selection process](https://thegooddocsproject.dev/proposal-selection.html), [Prioritization guidelines](https://thegooddocsproject.dev/prioritization.html), [Opencollective account to receive money](https://opencollective.com/thegooddocsproject)  (Cameron, Erin, multiple others)
* Welcome committee setup (Aidan)
* Describe onboarding process (Derek, Alyssa, Morgan, Felicity)

**Comment by camerons** [comment]
@barbaricyawps has started material for a jump page: https://docs.google.com/document/d/1rDTngrVNaGVA05aUL7owcZH0Q6sd8SjX5MiKZNZ3PWg/edit#

**Comment by bwklein** [comment]
List Page for Working Groups: https://thegooddocsproject.dev/working-group/
Example Working Group Details Page: https://thegooddocsproject.dev/working-group/doctools-easy-button/

@camerons do these pages and new 'working-group' content section/type meet the needs of this request?

If they do, then should we close this issue and make a new set for all the outstanding groups, or leave this open until all relevant groups are represented in the site?

**Comment by camerons** [comment]
Thanks @bwklein , yes I think the working groups page addresses the needs of this task for the moment. (There are still a couple of edge projects which are not listed, but we can add them later as interest picks up.)
