### ISSUE TITLE
Setup Gitpod for web based editing option.

### ISSUE THREAD

**Issue by bwklein** [thegooddocsproject/website-hugo#37]
Github has Gitpod integration, this will allow someone in the project to open an online editor and make changes/commits directly through the web without the need for a local dev environment.

I have done this for one of my internal projects, so I should be able to help with this or do it myself.

**Comment by mgan59** [comment]
I like this idea @bwklein and had a community member ask how they could help with the Hugo project.  An the first thought was to write docs around setting up and running Hugo, but could see having instructions to use Gitpod would be nice as well.

**Comment by bwklein** [comment]
There is an 'Open Source' option that gives people 50 hours per month on public projects.
https://www.gitpod.io/pricing/

**Comment by bwklein** [comment]
Implemented
