### ISSUE TITLE
Add themes to gitignore

### ISSUE THREAD

**Issue by mgan59** [thegooddocsproject/website-hugo#6]
## Context

Saw post setup that I had `themes/docsy` from setting up the submodule.  This directory is not part of the `.gitignore` and was almost committed.

More of an __Open Question__.  Do we/Should we version this folder?  Or exclude it?  Do we fork the docsy theme and then refer to our fork as the sub-module in our build?  I'm not sure the best practice here.  I can see the pros/cons of each.  I surface this because I could easily see someone else coming along setting up this project and accidentally committing the `themes/docsy` folder as part of a PR not realizing it.

## Actions

Proposing for now we add `themes/*` to the `.gitignore` so we ignore that theme folder/git module for now.  If/when we are ready to version the theme ourselves (most likely we are making alterations to it) we can cross that bridge.  

Also propose we capture this inside of an [ADR](https://github.com/joelparkerhenderson/architecture_decision_record). -- I prefer Michael Nygards light-weight version.

**Comment by bwklein** [comment]
As discussed in chat, If we get submodules working correctly in the project, we should not need to ignore this folder.

**Comment by mgan59** [comment]
Fixed as part of PR #7
