### ISSUE TITLE
Multiple author support

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#70]
**Is your feature request related to a problem? Please describe.**
We want to cover an article having multiple authors easily

**Describe the solution you'd like**
Multiple authors should work the same as individual authors: connecting to individual author JSON pages, rendering follow lines, etc. Order authors by order in JSON, not necessarily by alpha. (aka leave it to the JSON to know the right order, for potential mini-politics reasons)

**Describe alternatives you've considered**
Doing it manually, which doesn't allow for scalability or quickly editing someone's deadname

**Additional context**
None, Brian is already aware of this.

**Comment by ryanmacklin** [comment]
This change also means altering the footer on the list page. We're removing the image from the author line, allowing for multiple authors

**Comment by ryanmacklin** [comment]
Format for author byline: "{author 1}, {author 2}, {author N}"
No "and" or ampersand, just comma sepearated

**Comment by ryanmacklin** [comment]
For individual author posts: Allow for the title ("Bryan Klein is a technical fellow") in the byline. For multiple authors, skip that part. Let's see what it looks like as "<link>{name}</link> &endash; {title}"

**Comment by bwklein** [comment]
Done
