### ISSUE TITLE
Swap "min read" with "word count"

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#71]
**Is your feature request related to a problem? Please describe.**
The "X min read" has an inherent assumption regarding neurotypicality I'd like to avoid

**Describe the solution you'd like**
Instead of a time estimation, display the article size in word count. ("X words")

**Describe alternatives you've considered**
Not doing this, which is less work since the former is already implemented.

**Additional context**
None.

**Comment by ryanmacklin** [comment]
Also change on list page, and anywhere else where min read might be referenced (is there anything like that on the author pages?)

**Comment by ryanmacklin** [comment]
Leave the clock, for now. It's still a time element.

**Comment by bwklein** [comment]
Done
