### ISSUE TITLE
Blog article copyright & license line

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#72]
**Is your feature request related to a problem? Please describe.**
Each blog post needs an article copyright & license line

**Describe the solution you'd like**
At the end of each article, under the tags and before the prev/next nav, put a copyright/license line in (as deprioritized copy).

Autogenerated format:
&copy; {year} {author(s)}, released under <link>Creative Commons {license}</link>

Blog header should allow for an override of this line, replacing the autogenerated copyright/license with something custom. If nonexistent or blank, use the autogenerated one

**Describe alternatives you've considered**
A requirement for this problem

**Additional context**
The license is still being debated. We may want to have a blog variable for the default article license.

**Comment by bwklein** [comment]
@ryanmacklin I think that this is already done.  Reopen this case if there is something I am missing.
