### ISSUE TITLE
Blog: seperate article copy and author follow line

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#73]
**Is your feature request related to a problem? Please describe.**
The article copy currently flows into the author line, which makes a potential strong conclusion feel weaker.

**Describe the solution you'd like**
Put in a spacer between body and follows. Make it a 25% HR, perhaps making it more stylized later.

**Describe alternatives you've considered**
Just italicizing the author follow (like Cracked.com does), some padding above the author line (first author line in case of multiple authors), doing nothing.

**Additional context**
None

**Comment by ryanmacklin** [comment]
Related, for multiple authors, have each author follow on its own line, in the same order as noted regarding credit order in issue 70

**Comment by bwklein** [comment]
Done
