### ISSUE TITLE
Blog: Allow for optional "updated on" date in byline

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#75]
**Is your feature request related to a problem? Please describe.**
In case we need to flag that a post was updaed on a later date, such as to address controversy, let's make sure we flag that in the byline area

**Describe the solution you'd like**
Have a field for the updated date in the blog file, which renders as:
{published date}, updated on {updated date}

Updated date can be the same date as published date! Render even if that's true

**Describe alternatives you've considered**
Solely having it in the body

**Additional context**
None

**Comment by bwklein** [comment]
Done
