### ISSUE TITLE
Spacing around word count in post boxes

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#79]
**Describe the bug**
Visual bug: word count spacing is too tight

**To Reproduce**
1. Load blog index page
2. Look at word count sections
 
**Expected behavior**
More spacing between sections, akin to what blog posts have
(I suspect this is due to a copy/paste issue since we were wrapping up our jam session)

**Additional context**
None

**Comment by bwklein** [comment]
Done
