### ISSUE TITLE
Minor alteration of GDP's general copyright notice

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#81]
**Is your feature request related to a problem? Please describe.**
There are cases of multiple copyright notices to different parts of content, thanks to the blog

**Describe the solution you'd like**
Given the case of multiple copyright instances on the site, I suggest adding "unless otherwise stated" or similar to the site's copyright footer

**Describe alternatives you've considered**
None, but this is meant as a conversation starter

**Additional context**
This issue is more of a general site governance case, filed as an issue here since it directly applies to website config

**Comment by bwklein** [comment]
Done
