### ISSUE TITLE
Add about page for blog

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#83]
**Is your feature request related to a problem? Please describe.**
We'll need a place to point out how to contribute to the blog, the blog's mission, identifying the publishers, possibly licensing notes. We could also have the bottom of it be an index of authors, if we aren't covering that with another page.

**Describe the solution you'd like**
A separate page under the blog site

**Describe alternatives you've considered**
Not having one

**Additional context**
None

**Comment by bwklein** [comment]
I will add in an about page in the blog section and someone can edit it to add content.

**Comment by bwklein** [comment]
@ryanmacklin what if we just add the information about the blog to the blog landing page (I assume it won't be a lot of text), followed by the paginated lists of posts and below that a grid of authors with links to their pages.

This way the `/blog` page provides all the information someone might need about the blog and the content it provides.

**Comment by bwklein** [comment]
I've made the change to the blog index page to include the markdown content in the `_index.md` file for the blog section.
See what you think.

**Comment by bwklein** [comment]
I'll close this now, please reopen or make a new issue if you need it to change.
