### ISSUE TITLE
License notice slightly too inclusive

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#84]
**Describe the bug**
I realized that as implemented, we claim the image associated with the blog post is also released under the same license. Which we shouldn't, because we don't have that agreement if we're just using stock photos for things.

**To Reproduce**
Look at a blog post with a default license line/

**Expected behavior**
Have copyright line say "Text of article &copy;..."
License line refers to that inherently with "Release under..."

**Comment by bwklein** [comment]
Does it make sense for it to say...

`Text of article © Creative Commons Attribution 4.0 International (CC BY 4.0)`

**Comment by bwklein** [comment]
I just reread this issue and understand the ask now.  I have made the updates as requested.
