### ISSUE TITLE
Revising License page per RFC-004

### ISSUE THREAD

**Issue by ryanmacklin** [thegooddocsproject/website-hugo#95]
**Describe the task**
Revise the license page per RFC-004

**Comment by bwklein** [comment]
@ryanmacklin this PR should also modify the LICENSE.md file in the root of the repo.

**Comment by bwklein** [comment]
Then I would add the additional details to the end of the license file.  To make it clear that there is more than just the CC license involved, and you could point to the 'license' page on the site for more information.
